# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('icon_1_url', models.TextField(blank=True, null=True)),
                ('icon_2_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
