# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
